### ISSUE TITLE
Upgrade to Hibernate 7.0

### ISSUE THREAD

**Issue by jfialli** [coherence-community/coherence-hibernate#179]
Incompatible API changes were made moving from Hibernate 6.6 to Hibernate 7.0.

Need to migrate implementation and tests to work with Hibernate 7.0.

Link to failed dependabot pull request to bump to Hibernate version to 7.0.
https://github.com/coherence-community/coherence-hibernate/actions/runs/15280237821/job/42977117241

Here are compilation failures:
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.0:testCompile (default-testCompile) on project coherence-hibernate-cache-core: Compilation failure: Compilation failure: 
Error:  /home/runner/work/coherence-hibernate/coherence-hibernate/coherence-hibernate-cache-core/src/test/java/org/hibernate/tutorial/EventManager.java:[62,16] cannot find symbol
Error:    symbol:   method save(org.hibernate.tutorial.domain.Event)
Error:    location: variable session of type org.hibernate.Session
Error:  /home/runner/work/coherence-hibernate/coherence-hibernate/coherence-hibernate-cache-core/src/test/java/org/hibernate/tutorial/EventManager.java:[99,16] cannot find symbol
Error:    symbol:   method save(org.hibernate.tutorial.domain.Person)
Error:    location: variable session of type org.hibernate.Session
Error:  /home/runner/work/coherence-hibernate/coherence-hibernate/coherence-hibernate-cache-core/src/test/java/org/hibernate/tutorial/EventManager.java:[115,43] incompatible types: void cannot be converted to org.hibernate.tutorial.domain.Event
Error:  /home/runner/work/coherence-hibernate/coherence-hibernate/coherence-hibernate-cache-core/src/test/java/org/hibernate/tutorial/EventManager.java:[127,17] cannot find symbol
Error:    symbol:   method update(org.hibernate.tutorial.domain.Person)
Error:    location: variable session2 of type org.hibernate.Session
Error:  /home/runner/work/coherence-hibernate/coherence-hibernate/coherence-hibernate-cache-core/src/test/java/org/hibernate/tutorial/EventManager.java:[136,44] incompatible types: void cannot be converted to org.hibernate.tutorial.domain.Person
Error:  -> [Help 1]
